import jsPDF from 'jspdf'
import { formatCurrency, formatDate } from '../utils/format'

function addHeader(doc, business, title, number) {
  doc.setFillColor(17, 24, 39)
  doc.rect(0, 0, 210, 28, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text(business?.name || 'Kanziy', 14, 12)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text(business?.address || '', 14, 19)
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text(title, 196, 12, { align: 'right' })
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text(number, 196, 19, { align: 'right' })
  doc.setTextColor(0, 0, 0)
}

function addFooter(doc, pageCount) {
  const pageHeight = doc.internal.pageSize.height
  doc.setDrawColor(229, 231, 235)
  doc.line(14, pageHeight - 20, 196, pageHeight - 20)
  doc.setFontSize(8)
  doc.setTextColor(107, 114, 128)
  doc.text('Generated by Kanziy Operations System', 14, pageHeight - 13)
  doc.text(`Page ${pageCount}`, 196, pageHeight - 13, { align: 'right' })
}

export function generateInvoice(order, business) {
  const doc = new jsPDF()
  addHeader(doc, business, 'INVOICE', order.invoice_number || order.order_number)

  doc.setFontSize(10)
  let y = 38

  // Customer info
  doc.setFont('helvetica', 'bold')
  doc.text('Bill To:', 14, y)
  doc.setFont('helvetica', 'normal')
  doc.text(order.customer_name || '', 14, y + 6)
  doc.text(order.customer_phone || '', 14, y + 12)
  doc.text(`${order.city || ''}, ${order.state || ''}`, 14, y + 18)
  if (order.address) doc.text(order.address, 14, y + 24)

  // Order info
  doc.setFont('helvetica', 'bold')
  doc.text('Order Details:', 120, y)
  doc.setFont('helvetica', 'normal')
  doc.text(`Date: ${formatDate(order.created_at)}`, 120, y + 6)
  doc.text(`Order: ${order.order_number}`, 120, y + 12)
  doc.text('Payment Terms: Payment on Delivery', 120, y + 18)

  y += 36

  // Items table header
  doc.setFillColor(243, 244, 246)
  doc.rect(14, y, 182, 9, 'F')
  doc.setFont('helvetica', 'bold')
  doc.text('Product', 16, y + 6)
  doc.text('Qty', 120, y + 6)
  doc.text('Unit Price', 145, y + 6)
  doc.text('Total', 182, y + 6, { align: 'right' })

  y += 14
  doc.setFont('helvetica', 'normal')

  const items = order.items || [{
    product_name: order.product_name,
    quantity: order.quantity,
    unit_price: order.unit_price,
    color: order.color,
    size: order.size
  }]

  items.forEach(item => {
    const name = item.color || item.size
      ? `${item.product_name} (${[item.color, item.size].filter(Boolean).join(', ')})`
      : item.product_name
    const lines = doc.splitTextToSize(name, 100)
    lines.forEach((line, i) => doc.text(line, 16, y + (i * 5)))
    doc.text(String(item.quantity || ''), 120, y)
    doc.text(formatCurrency(item.unit_price), 145, y)
    doc.text(formatCurrency((item.quantity || 1) * (item.unit_price || 0)), 182, y, { align: 'right' })
    y += Math.max(lines.length * 5, 8) + 2
  })

  // Totals
  y += 4
  doc.setDrawColor(229, 231, 235)
  doc.line(14, y, 196, y)
  y += 6
  doc.setFont('helvetica', 'bold')
  doc.text('Total Amount:', 140, y)
  doc.text(formatCurrency(order.total_amount), 196, y, { align: 'right' })

  if (order.delivery_note) {
    y += 16
    doc.setFont('helvetica', 'bold')
    doc.text('Delivery Note:', 14, y)
    doc.setFont('helvetica', 'normal')
    y += 6
    const noteLines = doc.splitTextToSize(order.delivery_note, 170)
    noteLines.forEach(line => { doc.text(line, 14, y); y += 5 })
  }

  addFooter(doc, 1)
  return doc
}

export function generateReceipt(order, business) {
  const doc = new jsPDF()
  addHeader(doc, business, 'RECEIPT', order.receipt_number || order.order_number.replace('ORD', 'RCP'))

  let y = 38
  doc.setFontSize(10)
  doc.setFont('helvetica', 'bold')
  doc.text('Received From:', 14, y)
  doc.setFont('helvetica', 'normal')
  doc.text(order.customer_name || '', 14, y + 6)
  doc.text(order.customer_phone || '', 14, y + 12)

  doc.setFont('helvetica', 'bold')
  doc.text('Receipt Info:', 120, y)
  doc.setFont('helvetica', 'normal')
  doc.text(`Date: ${formatDate(order.paid_at || order.updated_at)}`, 120, y + 6)
  doc.text(`Order: ${order.order_number}`, 120, y + 12)

  y += 30
  doc.setFillColor(243, 244, 246)
  doc.rect(14, y, 182, 9, 'F')
  doc.setFont('helvetica', 'bold')
  doc.text('Description', 16, y + 6)
  doc.text('Amount', 182, y + 6, { align: 'right' })

  y += 14
  doc.setFont('helvetica', 'normal')
  doc.text(order.product_name || 'Products', 16, y)
  doc.text(formatCurrency(order.total_amount), 182, y, { align: 'right' })

  y += 14
  doc.setDrawColor(229, 231, 235)
  doc.line(14, y, 196, y)
  y += 6
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(12)
  doc.text('AMOUNT PAID:', 140, y)
  doc.text(formatCurrency(order.amount_paid || order.total_amount), 196, y, { align: 'right' })

  y += 16
  doc.setFontSize(10)
  doc.setTextColor(21, 128, 61)
  doc.setFont('helvetica', 'bold')
  doc.text('PAYMENT CONFIRMED', 105, y, { align: 'center' })
  doc.setTextColor(0, 0, 0)

  addFooter(doc, 1)
  return doc
}

export function generateDeliveryNote(order, business) {
  const doc = new jsPDF()
  addHeader(doc, business, 'DELIVERY NOTE', order.order_number)

  let y = 38
  doc.setFontSize(10)

  doc.setFont('helvetica', 'bold')
  doc.text('Deliver To:', 14, y)
  doc.setFont('helvetica', 'normal')
  doc.text(order.customer_name || '', 14, y + 6)
  doc.text(order.customer_phone || '', 14, y + 12)
  const addr = [order.address, order.city, order.state].filter(Boolean).join(', ')
  const addrLines = doc.splitTextToSize(addr, 90)
  addrLines.forEach((line, i) => doc.text(line, 14, y + 18 + (i * 5)))

  doc.setFont('helvetica', 'bold')
  doc.text('Delivery Info:', 120, y)
  doc.setFont('helvetica', 'normal')
  doc.text(`Order: ${order.order_number}`, 120, y + 6)
  doc.text(`Date: ${formatDate(order.planned_delivery_date || order.created_at)}`, 120, y + 12)
  if (order.preferred_delivery_time) doc.text(`Window: ${order.preferred_delivery_time}`, 120, y + 18)

  y += 42

  doc.setFillColor(243, 244, 246)
  doc.rect(14, y, 182, 9, 'F')
  doc.setFont('helvetica', 'bold')
  doc.text('Product', 16, y + 6)
  doc.text('Qty', 150, y + 6)
  doc.text('Notes', 164, y + 6)

  y += 14
  doc.setFont('helvetica', 'normal')
  const name = [order.product_name, order.color, order.size].filter(Boolean).join(' · ')
  doc.text(name, 16, y)
  doc.text(String(order.quantity || 1), 150, y)
  if (order.delivery_note) {
    const notes = doc.splitTextToSize(order.delivery_note, 30)
    notes.forEach((n, i) => doc.text(n, 164, y + i * 5))
  }

  y += 24
  doc.text('Received by: ___________________________', 14, y)
  doc.text('Signature: ___________________________', 14, y + 12)
  doc.text('Date: ___________________________', 14, y + 24)

  addFooter(doc, 1)
  return doc
}

export function generatePackingList(batch, packingItems, batchOrders, orderItems = []) {
  const doc = new jsPDF()
  doc.setFillColor(17, 24, 39)
  doc.rect(0, 0, 210, 28, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text('PACKING LIST', 14, 12)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text(batch.batch_number, 14, 19)
  doc.text(batch.courier_company || '', 196, 12, { align: 'right' })
  doc.text(batch.destination_state || '', 196, 19, { align: 'right' })
  doc.setTextColor(0, 0, 0)

  let y = 38
  doc.setFontSize(10)
  doc.setFont('helvetica', 'bold')
  doc.text(`Date: ${formatDate(batch.date_shipped || batch.created_at)}`, 14, y)
  doc.text(`Orders: ${batchOrders.length}`, 120, y)
  y += 10

  // Build per-state item list from actual order_items when available,
  // falling back to the stored packingItems for older batches.
  const itemsByOrderId = {}
  for (const oi of orderItems) {
    if (!itemsByOrderId[oi.order_id]) itemsByOrderId[oi.order_id] = []
    itemsByOrderId[oi.order_id].push(oi)
  }

  // Derive destination states from orders
  const states = [...new Set(batchOrders.map(bo => bo.order?.state).filter(Boolean))].sort()

  // Packed status lookup from stored packingItems (keyed by state+product_name)
  const packedLookup = {}
  for (const pi of packingItems) {
    packedLookup[`${pi.state}||${pi.product_name}`] = pi.is_packed
  }

  for (const state of states) {
    const stateOrders = batchOrders.filter(bo => bo.order?.state === state)

    // Aggregate items for this state
    const grouped = {}
    for (const bo of stateOrders) {
      // Priority: items_data JSONB > order_items table > order summary
      const fromJson = Array.isArray(bo.order?.items_data) && bo.order.items_data.length > 0
        ? bo.order.items_data : null
      const fromTable = itemsByOrderId[bo.order?.id]?.length > 0
        ? itemsByOrderId[bo.order.id] : null
      const lineItems = fromJson || fromTable
        || [{ product_name: bo.order?.product_name, quantity: bo.order?.quantity || 1, color: bo.order?.color, size: bo.order?.size }]

      for (const li of lineItems) {
        const label = [li.product_name, li.color, li.size].filter(Boolean).join(' — ')
        if (!grouped[label]) grouped[label] = { label, quantity: 0, isPacked: packedLookup[`${state}||${li.product_name}`] || false }
        grouped[label].quantity += Number(li.quantity) || 1
      }
    }

    doc.setFillColor(243, 244, 246)
    doc.rect(14, y, 182, 8, 'F')
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(10)
    doc.text(state, 16, y + 5.5)
    y += 12

    doc.setFont('helvetica', 'normal')
    doc.setFontSize(9)
    for (const { label, quantity, isPacked } of Object.values(grouped)) {
      const check = isPacked ? '[X]' : '[ ]'
      doc.text(check, 16, y)
      const nameLines = doc.splitTextToSize(label, 130)
      nameLines.forEach((line, i) => doc.text(line, 28, y + i * 5))
      doc.text(`Qty: ${quantity}`, 196, y, { align: 'right' })
      y += Math.max(nameLines.length * 5, 7) + 2
      if (y > 270) { doc.addPage(); y = 20 }
    }
    y += 4
  }

  y += 10
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.text('Packed by: ______________________________', 14, y)
  doc.text('Date: ______________________________', 120, y)

  addFooter(doc, 1)
  return doc
}

export function generateWaybillSummary(batch, batchOrders, expenses) {
  const doc = new jsPDF()
  doc.setFillColor(17, 24, 39)
  doc.rect(0, 0, 210, 28, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text('WAYBILL SUMMARY', 14, 12)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text(batch.batch_number, 14, 19)
  doc.text(batch.courier_company || '', 196, 12, { align: 'right' })
  doc.text(batch.tracking_number || '', 196, 19, { align: 'right' })
  doc.setTextColor(0, 0, 0)

  let y = 38
  doc.setFontSize(10)
  doc.setFont('helvetica', 'bold')
  doc.text('Batch Info', 14, y)
  doc.setFont('helvetica', 'normal')
  y += 7
  doc.text(`Destination: ${batch.destination_state || '—'}`, 14, y)
  doc.text(`Date Shipped: ${formatDate(batch.date_shipped || batch.created_at)}`, 120, y)
  y += 6
  doc.text(`Status: ${batch.status}`, 14, y)
  doc.text(`Orders: ${batchOrders.length}`, 120, y)
  y += 12

  // Orders table
  doc.setFillColor(243, 244, 246)
  doc.rect(14, y, 182, 8, 'F')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(9)
  doc.text('#', 16, y + 5.5)
  doc.text('Customer', 24, y + 5.5)
  doc.text('Product', 90, y + 5.5)
  doc.text('State', 140, y + 5.5)
  doc.text('Amount', 196, y + 5.5, { align: 'right' })
  y += 12

  doc.setFont('helvetica', 'normal')
  let total = 0
  batchOrders.forEach((bo, idx) => {
    const o = bo.order || bo
    doc.text(String(idx + 1), 16, y)
    doc.text(doc.splitTextToSize(o.customer_name || '', 62)[0], 24, y)
    doc.text(doc.splitTextToSize(o.product_name || '', 46)[0], 90, y)
    doc.text(o.state || '', 140, y)
    doc.text(formatCurrency(o.total_amount || 0), 196, y, { align: 'right' })
    total += Number(o.total_amount || 0)
    y += 7
    if (y > 265) { doc.addPage(); y = 20 }
  })

  y += 4
  doc.setDrawColor(229, 231, 235)
  doc.line(14, y, 196, y)
  y += 6
  doc.setFont('helvetica', 'bold')
  doc.text('Orders Total:', 140, y)
  doc.text(formatCurrency(total), 196, y, { align: 'right' })

  // Expenses
  if (expenses && Object.values(expenses).some(v => Number(v) > 0)) {
    y += 12
    doc.text('Logistics Expenses', 14, y)
    y += 8
    doc.setFont('helvetica', 'normal')
    const expenseRows = [
      ['Waybill Fee', expenses.waybill_cost],
      ['Packaging', expenses.packaging_cost],
      ['Loading', expenses.loading_cost],
      ['Transport', expenses.transport_cost],
      ['Dispatch', expenses.dispatch_cost],
      ['Other', expenses.other_cost],
    ]
    for (const [label, val] of expenseRows) {
      if (Number(val) > 0) {
        doc.text(label, 24, y)
        doc.text(formatCurrency(val), 196, y, { align: 'right' })
        y += 7
      }
    }
    const expTotal = expenseRows.reduce((s, [, v]) => s + (Number(v) || 0), 0)
    doc.setFont('helvetica', 'bold')
    doc.text('Logistics Total:', 140, y)
    doc.text(formatCurrency(expTotal), 196, y, { align: 'right' })
  }

  addFooter(doc, 1)
  return doc
}

export function savePdf(doc, filename) {
  doc.save(filename)
}
