import jsPDF from 'jspdf'
import { formatCurrency, formatDate } from '../utils/format'

function addHeader(doc, business, title, number) {
  doc.setFillColor(30, 64, 175)
  doc.rect(0, 0, 210, 28, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text(business?.name || 'Kanziy', 14, 12)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text(business?.address || '', 14, 19)
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text(title, 196, 12, { align: 'right' })
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text(number, 196, 19, { align: 'right' })
  doc.setTextColor(0, 0, 0)
}

function addFooter(doc, pageCount) {
  const pageHeight = doc.internal.pageSize.height
  doc.setDrawColor(229, 231, 235)
  doc.line(14, pageHeight - 20, 196, pageHeight - 20)
  doc.setFontSize(8)
  doc.setTextColor(107, 114, 128)
  doc.text('Generated by Kanziy Operations System', 14, pageHeight - 13)
  doc.text(`Page ${pageCount}`, 196, pageHeight - 13, { align: 'right' })
}

export function generateInvoice(order, business) {
  const doc = new jsPDF()
  addHeader(doc, business, 'INVOICE', order.invoice_number || order.order_number)

  doc.setFontSize(10)
  let y = 38

  // Customer info
  doc.setFont('helvetica', 'bold')
  doc.text('Bill To:', 14, y)
  doc.setFont('helvetica', 'normal')
  doc.text(order.customer_name || '', 14, y + 6)
  doc.text(order.customer_phone || '', 14, y + 12)
  doc.text(`${order.city || ''}, ${order.state || ''}`, 14, y + 18)
  if (order.address) doc.text(order.address, 14, y + 24)

  // Order info
  doc.setFont('helvetica', 'bold')
  doc.text('Order Details:', 120, y)
  doc.setFont('helvetica', 'normal')
  doc.text(`Date: ${formatDate(order.created_at)}`, 120, y + 6)
  doc.text(`Order: ${order.order_number}`, 120, y + 12)
  doc.text('Payment Terms: Payment on Delivery', 120, y + 18)

  y += 36

  // Items table header
  doc.setFillColor(243, 244, 246)
  doc.rect(14, y, 182, 9, 'F')
  doc.setFont('helvetica', 'bold')
  doc.text('Product', 16, y + 6)
  doc.text('Qty', 120, y + 6)
  doc.text('Unit Price', 145, y + 6)
  doc.text('Total', 182, y + 6, { align: 'right' })

  y += 14
  doc.setFont('helvetica', 'normal')

  const items = order.items || [{
    product_name: order.product_name,
    quantity: order.quantity,
    unit_price: order.unit_price,
    color: order.color,
    size: order.size
  }]

  items.forEach(item => {
    const name = item.color || item.size
      ? `${item.product_name} (${[item.color, item.size].filter(Boolean).join(', ')})`
      : item.product_name
    const lines = doc.splitTextToSize(name, 100)
    lines.forEach((line, i) => doc.text(line, 16, y + (i * 5)))
    doc.text(String(item.quantity || ''), 120, y)
    doc.text(formatCurrency(item.unit_price), 145, y)
    doc.text(formatCurrency((item.quantity || 1) * (item.unit_price || 0)), 182, y, { align: 'right' })
    y += Math.max(lines.length * 5, 8) + 2
  })

  // Totals
  y += 4
  doc.setDrawColor(229, 231, 235)
  doc.line(14, y, 196, y)
  y += 6
  doc.setFont('helvetica', 'bold')
  doc.text('Total Amount:', 140, y)
  doc.text(formatCurrency(order.total_amount), 196, y, { align: 'right' })

  if (order.delivery_note) {
    y += 16
    doc.setFont('helvetica', 'bold')
    doc.text('Delivery Note:', 14, y)
    doc.setFont('helvetica', 'normal')
    y += 6
    const noteLines = doc.splitTextToSize(order.delivery_note, 170)
    noteLines.forEach(line => { doc.text(line, 14, y); y += 5 })
  }

  addFooter(doc, 1)
  return doc
}

export function generateReceipt(order, business) {
  const doc = new jsPDF()
  addHeader(doc, business, 'RECEIPT', order.receipt_number || order.order_number.replace('ORD', 'RCP'))

  let y = 38
  doc.setFontSize(10)
  doc.setFont('helvetica', 'bold')
  doc.text('Received From:', 14, y)
  doc.setFont('helvetica', 'normal')
  doc.text(order.customer_name || '', 14, y + 6)
  doc.text(order.customer_phone || '', 14, y + 12)

  doc.setFont('helvetica', 'bold')
  doc.text('Receipt Info:', 120, y)
  doc.setFont('helvetica', 'normal')
  doc.text(`Date: ${formatDate(order.paid_at || order.updated_at)}`, 120, y + 6)
  doc.text(`Order: ${order.order_number}`, 120, y + 12)

  y += 30
  doc.setFillColor(243, 244, 246)
  doc.rect(14, y, 182, 9, 'F')
  doc.setFont('helvetica', 'bold')
  doc.text('Description', 16, y + 6)
  doc.text('Amount', 182, y + 6, { align: 'right' })

  y += 14
  doc.setFont('helvetica', 'normal')
  doc.text(order.product_name || 'Products', 16, y)
  doc.text(formatCurrency(order.total_amount), 182, y, { align: 'right' })

  y += 14
  doc.setDrawColor(229, 231, 235)
  doc.line(14, y, 196, y)
  y += 6
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(12)
  doc.text('AMOUNT PAID:', 140, y)
  doc.text(formatCurrency(order.amount_paid || order.total_amount), 196, y, { align: 'right' })

  y += 16
  doc.setFontSize(10)
  doc.setTextColor(21, 128, 61)
  doc.setFont('helvetica', 'bold')
  doc.text('PAYMENT CONFIRMED', 105, y, { align: 'center' })
  doc.setTextColor(0, 0, 0)

  addFooter(doc, 1)
  return doc
}

export function generateDeliveryNote(order, business) {
  const doc = new jsPDF()
  addHeader(doc, business, 'DELIVERY NOTE', order.order_number)

  let y = 38
  doc.setFontSize(10)

  doc.setFont('helvetica', 'bold')
  doc.text('Deliver To:', 14, y)
  doc.setFont('helvetica', 'normal')
  doc.text(order.customer_name || '', 14, y + 6)
  doc.text(order.customer_phone || '', 14, y + 12)
  const addr = [order.address, order.city, order.state].filter(Boolean).join(', ')
  const addrLines = doc.splitTextToSize(addr, 90)
  addrLines.forEach((line, i) => doc.text(line, 14, y + 18 + (i * 5)))

  doc.setFont('helvetica', 'bold')
  doc.text('Delivery Info:', 120, y)
  doc.setFont('helvetica', 'normal')
  doc.text(`Order: ${order.order_number}`, 120, y + 6)
  doc.text(`Date: ${formatDate(order.planned_delivery_date || order.created_at)}`, 120, y + 12)
  if (order.preferred_delivery_time) doc.text(`Window: ${order.preferred_delivery_time}`, 120, y + 18)

  y += 42

  doc.setFillColor(243, 244, 246)
  doc.rect(14, y, 182, 9, 'F')
  doc.setFont('helvetica', 'bold')
  doc.text('Product', 16, y + 6)
  doc.text('Qty', 150, y + 6)
  doc.text('Notes', 164, y + 6)

  y += 14
  doc.setFont('helvetica', 'normal')
  const name = [order.product_name, order.color, order.size].filter(Boolean).join(' · ')
  doc.text(name, 16, y)
  doc.text(String(order.quantity || 1), 150, y)
  if (order.delivery_note) {
    const notes = doc.splitTextToSize(order.delivery_note, 30)
    notes.forEach((n, i) => doc.text(n, 164, y + i * 5))
  }

  y += 24
  doc.text('Received by: ___________________________', 14, y)
  doc.text('Signature: ___________________________', 14, y + 12)
  doc.text('Date: ___________________________', 14, y + 24)

  addFooter(doc, 1)
  return doc
}

export function savePdf(doc, filename) {
  doc.save(filename)
}
