import jsPDF from 'jspdf'
import { formatCurrency, formatDate } from '../utils/format'
import { supabase } from './supabase'

function addHeader(doc, business, title, number) {
  doc.setFillColor(17, 24, 39)
  doc.rect(0, 0, 210, 28, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text(business?.name || 'Kanziy', 14, 12)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text(business?.address || '', 14, 19)
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text(title, 196, 12, { align: 'right' })
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text(number, 196, 19, { align: 'right' })
  doc.setTextColor(0, 0, 0)
}

function addFooter(doc, pageCount) {
  const pageHeight = doc.internal.pageSize.height
  doc.setDrawColor(229, 231, 235)
  doc.line(14, pageHeight - 20, 196, pageHeight - 20)
  doc.setFontSize(8)
  doc.setTextColor(107, 114, 128)
  doc.text('Generated by Kanziy Operations System', 14, pageHeight - 13)
  doc.text(`Page ${pageCount}`, 196, pageHeight - 13, { align: 'right' })
}

// ═══════════════════════════════════════════════════════════════════
// Invoice — premium ERP-style layout (A4 portrait)
// ═══════════════════════════════════════════════════════════════════

// Brand accent (gold) and neutrals used sparingly per the design spec
const INK    = [17, 24, 39]     // gray-900 — titles, key figures
const MUTED  = [107, 114, 128]  // gray-500 — labels, secondary text
const FAINT  = [156, 163, 175]  // gray-400 — footer, hints
const RULE   = [229, 231, 235]  // gray-200 — hairlines
const ACCENT = [202, 138, 4]    // gold — accents only

const M = 18                    // page margin (mm)
const PAGE_W = 210
const RIGHT = PAGE_W - M        // 192
const BODY_BOTTOM = 252         // content stops here; footer zone below

// jsPDF's built-in fonts have no naira glyph, so invoices use NGN
const money = (n) =>
  'NGN ' + Number(n || 0).toLocaleString('en-NG', { minimumFractionDigits: 2, maximumFractionDigits: 2 })

async function loadImageData(url) {
  try {
    const res = await fetch(url, { mode: 'cors' })
    if (!res.ok) return null
    const blob = await res.blob()
    return await new Promise((resolve) => {
      const r = new FileReader()
      r.onload = () => resolve(r.result)
      r.onerror = () => resolve(null)
      r.readAsDataURL(blob)
    })
  } catch { return null }
}

function invoiceFooters(doc, business) {
  const pages = doc.getNumberOfPages()
  const h = doc.internal.pageSize.height
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i)
    doc.setDrawColor(...RULE)
    doc.setLineWidth(0.2)
    doc.line(M, h - 22, RIGHT, h - 22)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(7.5)
    doc.setTextColor(...FAINT)
    doc.text('Generated by MaalOps ERP — this invoice was generated automatically.', M, h - 16)
    doc.text(`© ${new Date().getFullYear()} ${business?.name || 'Kanziy'}. All rights reserved.`, M, h - 11.5)
    doc.text(`Page ${i} of ${pages}`, RIGHT, h - 16, { align: 'right' })
  }
}

export async function generateInvoice(order, businessIn) {
  // List views only carry a slim business object — pull the full
  // branding (address, bank details, logo) when it's missing
  let business = businessIn
  if (business?.id && business.bank_name === undefined && business.logo_url === undefined) {
    try {
      const { data } = await supabase.from('businesses').select('*').eq('id', business.id).single()
      if (data) business = data
    } catch { /* keep the slim object */ }
  }

  const doc = new jsPDF({ unit: 'mm', format: 'a4' })

  // ── Header ─────────────────────────────────────────────────────────
  const logoData = business?.logo_url ? await loadImageData(business.logo_url) : null
  let leftY = 20
  if (logoData) {
    try { doc.addImage(logoData, undefined, M, 15, 18, 18) } catch { /* bad image */ }
  } else {
    // Monogram fallback: initial on an ink square
    doc.setFillColor(...INK)
    doc.roundedRect(M, 15, 16, 16, 2.5, 2.5, 'F')
    doc.setTextColor(255, 255, 255)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(13)
    doc.text((business?.name || 'K')[0].toUpperCase(), M + 8, 25.5, { align: 'center' })
  }
  const nameX = M + (logoData ? 22 : 20)
  doc.setTextColor(...INK)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(13)
  doc.text(business?.name || 'Kanziy', nameX, 20.5)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  doc.setTextColor(...MUTED)
  let infoY = 25.5
  for (const line of [business?.address, business?.phone, business?.email, business?.website].filter(Boolean)) {
    doc.text(String(line), nameX, infoY, { maxWidth: 82 })
    infoY += 4
  }
  leftY = Math.max(33, infoY)

  // Right side: INVOICE + meta
  doc.setTextColor(...INK)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(24)
  doc.text('INVOICE', RIGHT, 23, { align: 'right' })
  const invoiceNumber = order.invoice_number
    || order.order_number.replace(/^ORD/, business?.invoice_prefix || 'INV')
  const meta = [
    ['Invoice No.', invoiceNumber],
    ['Invoice Date', formatDate(order.created_at)],
    ['Order No.', order.order_number],
    ['Payment Terms', 'Payment on Delivery'],
  ]
  if (order.balance_due_date) meta.push(['Due Date', formatDate(order.balance_due_date)])
  let metaY = 30.5
  doc.setFontSize(8.5)
  for (const [label, value] of meta) {
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...MUTED)
    doc.text(label, RIGHT - 42, metaY, { align: 'right' })
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...INK)
    doc.text(String(value), RIGHT, metaY, { align: 'right' })
    metaY += 4.8
  }

  // Gold accent rule closing the header
  let y = Math.max(leftY, metaY) + 4
  doc.setDrawColor(...ACCENT)
  doc.setLineWidth(0.7)
  doc.line(M, y, RIGHT, y)
  y += 10

  // ── Bill To ────────────────────────────────────────────────────────
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(7.5)
  doc.setTextColor(...ACCENT)
  doc.text('BILL TO', M, y, { charSpace: 0.6 })
  y += 5
  doc.setTextColor(...INK)
  doc.setFontSize(10.5)
  doc.text(order.customer_name || '', M, y)
  y += 5
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8.5)
  doc.setTextColor(...MUTED)
  const custLines = [
    order.customer_phone,
    order.address,
    [order.city, order.state].filter(Boolean).join(', '),
    order.customer_email,
  ].filter(Boolean)
  for (const line of custLines) {
    const wrapped = doc.splitTextToSize(String(line), 95)
    for (const w of wrapped) { doc.text(w, M, y); y += 4.2 }
  }
  y += 7

  // ── Product table ──────────────────────────────────────────────────
  const COL_QTY = 128, COL_PRICE = 162, NAME_W = 88
  const drawTableHead = () => {
    doc.setDrawColor(...INK)
    doc.setLineWidth(0.4)
    doc.line(M, y, RIGHT, y)
    y += 5
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(7.5)
    doc.setTextColor(...MUTED)
    doc.text('PRODUCT', M, y, { charSpace: 0.5 })
    doc.text('QTY', COL_QTY, y, { align: 'right', charSpace: 0.5 })
    doc.text('UNIT PRICE', COL_PRICE, y, { align: 'right', charSpace: 0.5 })
    doc.text('TOTAL', RIGHT, y, { align: 'right', charSpace: 0.5 })
    y += 2.5
    doc.setDrawColor(...RULE)
    doc.setLineWidth(0.2)
    doc.line(M, y, RIGHT, y)
    y += 6
  }
  drawTableHead()

  const items = (Array.isArray(order.items_data) && order.items_data.length > 0)
    ? order.items_data
    : (order.items && order.items.length > 0)
    ? order.items
    : [{
        product_name: order.product_name, quantity: order.quantity,
        unit_price: order.unit_price, color: order.color, size: order.size,
      }]

  let subtotal = 0
  for (const item of items) {
    const qty = Number(item.quantity) || 1
    const price = Number(item.unit_price) || 0
    const lineTotal = item.total_amount != null ? Number(item.total_amount) : qty * price
    subtotal += lineTotal

    const nameLines = doc.splitTextToSize(String(item.product_name || ''), NAME_W)
    const desc = [item.color, item.size].filter(Boolean).join(' · ')
    const rowH = nameLines.length * 4.4 + (desc ? 4 : 0) + 4.5

    if (y + rowH > BODY_BOTTOM) {
      doc.addPage()
      y = 20
      drawTableHead()
    }

    doc.setFont('helvetica', 'normal')
    doc.setFontSize(9.5)
    doc.setTextColor(...INK)
    nameLines.forEach((line, i) => doc.text(line, M, y + i * 4.4))
    if (desc) {
      doc.setFontSize(8)
      doc.setTextColor(...MUTED)
      doc.text(desc, M, y + nameLines.length * 4.4)
    }
    doc.setFontSize(9.5)
    doc.setTextColor(...INK)
    doc.text(String(qty), COL_QTY, y, { align: 'right' })
    doc.text(money(price), COL_PRICE, y, { align: 'right' })
    doc.setFont('helvetica', 'bold')
    doc.text(money(lineTotal), RIGHT, y, { align: 'right' })

    y += rowH - 2
    doc.setDrawColor(...RULE)
    doc.setLineWidth(0.15)
    doc.line(M, y, RIGHT, y)
    y += 4.5
  }

  // ── Financial summary (right) + payment info (left) ───────────────
  if (y + 55 > BODY_BOTTOM) { doc.addPage(); y = 20 }
  y += 3
  const sumLabelX = 122, blockTop = y
  const discount = Number(order.discount) || 0
  const grand = Number(order.total_amount) || subtotal - discount

  const sumRow = (label, value, opts = {}) => {
    doc.setFont('helvetica', opts.bold ? 'bold' : 'normal')
    doc.setFontSize(opts.size || 9)
    doc.setTextColor(...(opts.labelColor || MUTED))
    doc.text(label, sumLabelX, y)
    doc.setTextColor(...(opts.valueColor || INK))
    doc.setFont('helvetica', 'bold')
    doc.text(value, RIGHT, y, { align: 'right' })
    y += opts.gap || 6
  }
  sumRow('Subtotal', money(subtotal))
  if (discount > 0) sumRow('Discount', `- ${money(discount)}`)
  sumRow('VAT', 'Inclusive')
  doc.setDrawColor(...INK)
  doc.setLineWidth(0.4)
  doc.line(sumLabelX, y - 2, RIGHT, y - 2)
  y += 3.5
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(8)
  doc.setTextColor(...INK)
  doc.text('GRAND TOTAL', sumLabelX, y, { charSpace: 0.5 })
  y += 7.5
  doc.setFontSize(14)
  doc.setTextColor(...ACCENT)
  doc.text(money(grand), RIGHT, y, { align: 'right' })
  const summaryBottom = y + 6

  // Payment information block, aligned with the summary
  let py = blockTop
  if (business?.bank_name || business?.bank_account_number) {
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(7.5)
    doc.setTextColor(...ACCENT)
    doc.text('PAYMENT INFORMATION', M, py, { charSpace: 0.6 })
    py += 5.5
    doc.setFontSize(8.5)
    const payRows = [
      ['Bank Name', business?.bank_name],
      ['Account Name', business?.bank_account_name],
      ['Account Number', business?.bank_account_number],
    ].filter(([, v]) => v)
    for (const [label, value] of payRows) {
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(...MUTED)
      doc.text(label, M, py)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(...INK)
      doc.text(String(value), M + 32, py)
      py += 4.8
    }
  }
  y = Math.max(summaryBottom, py) + 10

  // ── Delivery note ──────────────────────────────────────────────────
  if (order.delivery_note) {
    if (y + 20 > BODY_BOTTOM) { doc.addPage(); y = 20 }
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(7.5)
    doc.setTextColor(...ACCENT)
    doc.text('DELIVERY NOTE', M, y, { charSpace: 0.6 })
    y += 5
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8.5)
    doc.setTextColor(...MUTED)
    const noteLines = doc.splitTextToSize(order.delivery_note, RIGHT - M)
    for (const line of noteLines) {
      if (y > BODY_BOTTOM) { doc.addPage(); y = 20 }
      doc.text(line, M, y); y += 4.2
    }
  }

  invoiceFooters(doc, business)
  doc.setTextColor(0, 0, 0)
  return doc
}

export function generateReceipt(order, business) {
  const doc = new jsPDF()
  addHeader(doc, business, 'RECEIPT', order.receipt_number || order.order_number.replace('ORD', 'RCP'))

  let y = 38
  doc.setFontSize(10)
  doc.setFont('helvetica', 'bold')
  doc.text('Received From:', 14, y)
  doc.setFont('helvetica', 'normal')
  doc.text(order.customer_name || '', 14, y + 6)
  doc.text(order.customer_phone || '', 14, y + 12)

  doc.setFont('helvetica', 'bold')
  doc.text('Receipt Info:', 120, y)
  doc.setFont('helvetica', 'normal')
  doc.text(`Date: ${formatDate(order.paid_at || order.updated_at)}`, 120, y + 6)
  doc.text(`Order: ${order.order_number}`, 120, y + 12)

  y += 30
  doc.setFillColor(243, 244, 246)
  doc.rect(14, y, 182, 9, 'F')
  doc.setFont('helvetica', 'bold')
  doc.text('Description', 16, y + 6)
  doc.text('Amount', 182, y + 6, { align: 'right' })

  y += 14
  doc.setFont('helvetica', 'normal')
  doc.text(order.product_name || 'Products', 16, y)
  doc.text(formatCurrency(order.total_amount), 182, y, { align: 'right' })

  y += 14
  doc.setDrawColor(229, 231, 235)
  doc.line(14, y, 196, y)
  y += 6
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(12)
  doc.text('AMOUNT PAID:', 140, y)
  doc.text(formatCurrency(order.amount_paid || order.total_amount), 196, y, { align: 'right' })

  y += 16
  doc.setFontSize(10)
  doc.setTextColor(21, 128, 61)
  doc.setFont('helvetica', 'bold')
  doc.text('PAYMENT CONFIRMED', 105, y, { align: 'center' })
  doc.setTextColor(0, 0, 0)

  addFooter(doc, 1)
  return doc
}

export function generateDeliveryNote(order, business) {
  const doc = new jsPDF()
  addHeader(doc, business, 'DELIVERY NOTE', order.order_number)

  let y = 38
  doc.setFontSize(10)

  doc.setFont('helvetica', 'bold')
  doc.text('Deliver To:', 14, y)
  doc.setFont('helvetica', 'normal')
  doc.text(order.customer_name || '', 14, y + 6)
  doc.text(order.customer_phone || '', 14, y + 12)
  const addr = [order.address, order.city, order.state].filter(Boolean).join(', ')
  const addrLines = doc.splitTextToSize(addr, 90)
  addrLines.forEach((line, i) => doc.text(line, 14, y + 18 + (i * 5)))

  doc.setFont('helvetica', 'bold')
  doc.text('Delivery Info:', 120, y)
  doc.setFont('helvetica', 'normal')
  doc.text(`Order: ${order.order_number}`, 120, y + 6)
  doc.text(`Date: ${formatDate(order.planned_delivery_date || order.created_at)}`, 120, y + 12)
  if (order.preferred_delivery_time) doc.text(`Window: ${order.preferred_delivery_time}`, 120, y + 18)

  y += 42

  doc.setFillColor(243, 244, 246)
  doc.rect(14, y, 182, 9, 'F')
  doc.setFont('helvetica', 'bold')
  doc.text('Product', 16, y + 6)
  doc.text('Qty', 150, y + 6)
  doc.text('Notes', 164, y + 6)

  y += 14
  doc.setFont('helvetica', 'normal')
  const name = [order.product_name, order.color, order.size].filter(Boolean).join(' · ')
  doc.text(name, 16, y)
  doc.text(String(order.quantity || 1), 150, y)
  if (order.delivery_note) {
    const notes = doc.splitTextToSize(order.delivery_note, 30)
    notes.forEach((n, i) => doc.text(n, 164, y + i * 5))
  }

  y += 24
  doc.text('Received by: ___________________________', 14, y)
  doc.text('Signature: ___________________________', 14, y + 12)
  doc.text('Date: ___________________________', 14, y + 24)

  addFooter(doc, 1)
  return doc
}

export function generatePackingList(batch, packingItems, batchOrders, orderItems = []) {
  const doc = new jsPDF()
  doc.setFillColor(17, 24, 39)
  doc.rect(0, 0, 210, 28, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text('PACKING LIST', 14, 12)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text(batch.batch_number, 14, 19)
  doc.text(batch.courier_company || '', 196, 12, { align: 'right' })
  doc.text(batch.destination_state || '', 196, 19, { align: 'right' })
  doc.setTextColor(0, 0, 0)

  let y = 38
  doc.setFontSize(10)
  doc.setFont('helvetica', 'bold')
  doc.text(`Date: ${formatDate(batch.date_shipped || batch.created_at)}`, 14, y)
  doc.text(`Orders: ${batchOrders.length}`, 120, y)
  y += 10

  // Build per-state item list from actual order_items when available,
  // falling back to the stored packingItems for older batches.
  const itemsByOrderId = {}
  for (const oi of orderItems) {
    if (!itemsByOrderId[oi.order_id]) itemsByOrderId[oi.order_id] = []
    itemsByOrderId[oi.order_id].push(oi)
  }

  // Derive destination states from orders
  const states = [...new Set(batchOrders.map(bo => bo.order?.state).filter(Boolean))].sort()

  // Packed status lookup from stored packingItems (keyed by state+product_name)
  const packedLookup = {}
  for (const pi of packingItems) {
    packedLookup[`${pi.state}||${pi.product_name}`] = pi.is_packed
  }

  for (const state of states) {
    const stateOrders = batchOrders.filter(bo => bo.order?.state === state)

    // Aggregate items for this state
    const grouped = {}
    for (const bo of stateOrders) {
      // Priority: items_data JSONB > order_items table > order summary
      const fromJson = Array.isArray(bo.order?.items_data) && bo.order.items_data.length > 0
        ? bo.order.items_data : null
      const fromTable = itemsByOrderId[bo.order?.id]?.length > 0
        ? itemsByOrderId[bo.order.id] : null
      const lineItems = fromJson || fromTable
        || [{ product_name: bo.order?.product_name, quantity: bo.order?.quantity || 1, color: bo.order?.color, size: bo.order?.size }]

      for (const li of lineItems) {
        const label = [li.product_name, li.color, li.size].filter(Boolean).join(' — ')
        if (!grouped[label]) grouped[label] = { label, quantity: 0, isPacked: packedLookup[`${state}||${li.product_name}`] || false }
        grouped[label].quantity += Number(li.quantity) || 1
      }
    }

    doc.setFillColor(243, 244, 246)
    doc.rect(14, y, 182, 8, 'F')
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(10)
    doc.text(state, 16, y + 5.5)
    y += 12

    doc.setFont('helvetica', 'normal')
    doc.setFontSize(9)
    for (const { label, quantity, isPacked } of Object.values(grouped)) {
      const check = isPacked ? '[X]' : '[ ]'
      doc.text(check, 16, y)
      const nameLines = doc.splitTextToSize(label, 130)
      nameLines.forEach((line, i) => doc.text(line, 28, y + i * 5))
      doc.text(`Qty: ${quantity}`, 196, y, { align: 'right' })
      y += Math.max(nameLines.length * 5, 7) + 2
      if (y > 270) { doc.addPage(); y = 20 }
    }
    y += 4
  }

  y += 10
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.text('Packed by: ______________________________', 14, y)
  doc.text('Date: ______________________________', 120, y)

  addFooter(doc, 1)
  return doc
}

export function generateWaybillSummary(batch, batchOrders, expenses) {
  const doc = new jsPDF()
  doc.setFillColor(17, 24, 39)
  doc.rect(0, 0, 210, 28, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text('WAYBILL SUMMARY', 14, 12)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text(batch.batch_number, 14, 19)
  doc.text(batch.courier_company || '', 196, 12, { align: 'right' })
  doc.text(batch.tracking_number || '', 196, 19, { align: 'right' })
  doc.setTextColor(0, 0, 0)

  let y = 38
  doc.setFontSize(10)
  doc.setFont('helvetica', 'bold')
  doc.text('Batch Info', 14, y)
  doc.setFont('helvetica', 'normal')
  y += 7
  doc.text(`Destination: ${batch.destination_state || '—'}`, 14, y)
  doc.text(`Date Shipped: ${formatDate(batch.date_shipped || batch.created_at)}`, 120, y)
  y += 6
  doc.text(`Status: ${batch.status}`, 14, y)
  doc.text(`Orders: ${batchOrders.length}`, 120, y)
  y += 12

  // Orders table
  doc.setFillColor(243, 244, 246)
  doc.rect(14, y, 182, 8, 'F')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(9)
  doc.text('#', 16, y + 5.5)
  doc.text('Customer', 24, y + 5.5)
  doc.text('Product', 90, y + 5.5)
  doc.text('State', 140, y + 5.5)
  doc.text('Amount', 196, y + 5.5, { align: 'right' })
  y += 12

  doc.setFont('helvetica', 'normal')
  let total = 0
  batchOrders.forEach((bo, idx) => {
    const o = bo.order || bo
    doc.text(String(idx + 1), 16, y)
    doc.text(doc.splitTextToSize(o.customer_name || '', 62)[0], 24, y)
    doc.text(doc.splitTextToSize(o.product_name || '', 46)[0], 90, y)
    doc.text(o.state || '', 140, y)
    doc.text(formatCurrency(o.total_amount || 0), 196, y, { align: 'right' })
    total += Number(o.total_amount || 0)
    y += 7
    if (y > 265) { doc.addPage(); y = 20 }
  })

  y += 4
  doc.setDrawColor(229, 231, 235)
  doc.line(14, y, 196, y)
  y += 6
  doc.setFont('helvetica', 'bold')
  doc.text('Orders Total:', 140, y)
  doc.text(formatCurrency(total), 196, y, { align: 'right' })

  // Expenses
  if (expenses && Object.values(expenses).some(v => Number(v) > 0)) {
    y += 12
    doc.text('Logistics Expenses', 14, y)
    y += 8
    doc.setFont('helvetica', 'normal')
    const expenseRows = [
      ['Waybill Fee', expenses.waybill_cost],
      ['Packaging', expenses.packaging_cost],
      ['Loading', expenses.loading_cost],
      ['Transport', expenses.transport_cost],
      ['Dispatch', expenses.dispatch_cost],
      ['Other', expenses.other_cost],
    ]
    for (const [label, val] of expenseRows) {
      if (Number(val) > 0) {
        doc.text(label, 24, y)
        doc.text(formatCurrency(val), 196, y, { align: 'right' })
        y += 7
      }
    }
    const expTotal = expenseRows.reduce((s, [, v]) => s + (Number(v) || 0), 0)
    doc.setFont('helvetica', 'bold')
    doc.text('Logistics Total:', 140, y)
    doc.text(formatCurrency(expTotal), 196, y, { align: 'right' })
  }

  addFooter(doc, 1)
  return doc
}

export function savePdf(doc, filename) {
  doc.save(filename)
}
