import jsPDF from 'jspdf'
import { labelOf, WARNING_TYPES } from '../hooks/useStaff'

function letterShell(doc, businessName, title) {
  doc.setFontSize(16); doc.setFont('helvetica', 'bold')
  doc.text(businessName || 'Company', 20, 20)
  doc.setDrawColor(200); doc.line(20, 24, 190, 24)
  doc.setFontSize(14)
  doc.text(title, 20, 36)
  doc.setFontSize(10); doc.setFont('helvetica', 'normal')
  return 46
}

function wrapText(doc, text, x, y, maxWidth = 170, lineHeight = 5.5) {
  const lines = doc.splitTextToSize(text || '', maxWidth)
  lines.forEach(line => {
    if (y > 275) { doc.addPage(); y = 20 }
    doc.text(line, x, y)
    y += lineHeight
  })
  return y
}

// Formal warning letter from a staff_warnings record
export function generateWarningLetter(warning, staff, businessName) {
  const doc = new jsPDF()
  let y = letterShell(doc, businessName, labelOf(WARNING_TYPES, warning.warning_type).toUpperCase())

  doc.text(`Date: ${warning.date_issued || ''}`, 20, y); y += 6
  doc.text(`To: ${staff?.name || ''} (${staff?.staff_code || ''})`, 20, y); y += 6
  if (staff?.position || staff?.department) {
    doc.text(`Position: ${[staff.position, staff.department].filter(Boolean).join(' · ')}`, 20, y); y += 6
  }
  y += 4

  const section = (heading, body) => {
    if (!body) return
    doc.setFont('helvetica', 'bold'); doc.text(heading, 20, y); y += 6
    doc.setFont('helvetica', 'normal')
    y = wrapText(doc, body, 20, y) + 4
  }

  if (warning.category) section('Category', warning.category)
  section('Incident Details', warning.incident_details)
  section('Corrective Action Required', warning.corrective_action)
  if (warning.review_date) section('Review Date', warning.review_date)
  section('Consequence If Not Improved', warning.consequence)

  y += 6
  doc.text(`Issued by: ${warning.issued_by_name || ''}`, 20, y); y += 14
  doc.text('Signature (Issuer): ______________________', 20, y); y += 10
  doc.text('Signature (Staff):  ______________________', 20, y)

  return doc
}

// Generic HR letter from a generated staff_documents record
export function generateStaffLetter(docRecord, staff, businessName) {
  const doc = new jsPDF()
  let y = letterShell(doc, businessName, docRecord.title)

  doc.text(`Date: ${(docRecord.created_at || '').slice(0, 10)}`, 20, y); y += 6
  doc.text(`To: ${staff?.name || ''} (${staff?.staff_code || ''})`, 20, y); y += 10

  y = wrapText(doc, docRecord.body || '', 20, y)

  y += 14
  doc.text(`Issued by: ${docRecord.uploaded_by_name || ''}`, 20, y); y += 12
  doc.text('Signature: ______________________', 20, y)

  return doc
}

// Employment contract PDF from a staff_contracts record (body text)
export function generateContractPdf(contract, staff, businessName) {
  const doc = new jsPDF()
  doc.setFontSize(15); doc.setFont('helvetica', 'bold')
  doc.text(businessName || 'Company', 20, 20)
  doc.setDrawColor(202, 138, 4); doc.setLineWidth(0.6); doc.line(20, 24, 190, 24)
  doc.setFontSize(9); doc.setFont('helvetica', 'normal'); doc.setTextColor(120)
  doc.text(`Employment Contract — Version ${contract.version} · ${contract.status.toUpperCase()}`, 20, 30)
  doc.setTextColor(0)

  let y = 40
  doc.setFontSize(10)
  for (const rawLine of (contract.body || '').split('\n')) {
    const isHeading = /^[0-9]+\.\s|^EMPLOYMENT CONTRACT/.test(rawLine.trim())
    doc.setFont('helvetica', isHeading ? 'bold' : 'normal')
    const lines = doc.splitTextToSize(rawLine || ' ', 170)
    for (const line of lines) {
      if (y > 275) { doc.addPage(); y = 20 }
      doc.text(line, 20, y)
      y += 5.5
    }
  }

  if (contract.accepted_at) {
    if (y > 260) { doc.addPage(); y = 20 }
    y += 6
    doc.setFont('helvetica', 'bold'); doc.setTextColor(21, 128, 61)
    doc.text(`Digitally accepted by ${contract.accepted_name || staff?.name} on ${new Date(contract.accepted_at).toLocaleString('en-NG')}`, 20, y)
    doc.setTextColor(0)
  }

  const h = doc.internal.pageSize.height
  doc.setFontSize(8); doc.setFont('helvetica', 'normal'); doc.setTextColor(150)
  doc.text('Generated by MaalOps ERP', 20, h - 10)
  return doc
}

// Digital staff ID card (ID-card proportions on an A5 landscape page)
export function generateStaffIdPdf(staff, profile, businessName) {
  const doc = new jsPDF({ orientation: 'landscape', format: 'a5', unit: 'mm' })
  // Card frame
  doc.setFillColor(17, 24, 39)
  doc.roundedRect(20, 15, 170, 100, 5, 5, 'F')
  doc.setFillColor(202, 138, 4)
  doc.rect(20, 15, 170, 8, 'F')

  doc.setTextColor(255, 255, 255)
  doc.setFont('helvetica', 'bold'); doc.setFontSize(14)
  doc.text(businessName || 'Company', 30, 38)
  doc.setFontSize(9); doc.setFont('helvetica', 'normal'); doc.setTextColor(180)
  doc.text('STAFF IDENTITY CARD', 30, 44)

  // Photo box (photo itself is a link; the box shows the initial)
  doc.setFillColor(55, 65, 81)
  doc.roundedRect(140, 32, 36, 44, 3, 3, 'F')
  doc.setTextColor(255, 255, 255); doc.setFont('helvetica', 'bold'); doc.setFontSize(26)
  doc.text((staff?.name || '?')[0].toUpperCase(), 158, 58, { align: 'center' })

  doc.setFontSize(16)
  doc.text(staff?.name || '', 30, 58)
  doc.setFontSize(10); doc.setFont('helvetica', 'normal'); doc.setTextColor(220)
  let y = 66
  for (const [label, value] of [
    ['Staff Code', staff?.staff_code],
    ['Job Title', staff?.position],
    ['Department', staff?.department],
    ['Work Location', staff?.work_location],
    ['Status', (staff?.status || 'active').replace(/_/g, ' ')],
  ]) {
    if (!value) continue
    doc.setTextColor(150); doc.text(`${label}:`, 30, y)
    doc.setTextColor(255); doc.text(String(value), 62, y)
    y += 6.5
  }

  doc.setFontSize(8); doc.setTextColor(180)
  doc.text(
    `Issued ${staff?.id_card_issued_at || ''}${staff?.id_card_expiry ? ` · Expires ${staff.id_card_expiry}` : ''}`,
    30, 110)
  doc.text('Property of the company. If found, please return.', 189, 110, { align: 'right' })
  return doc
}
